services:
    kejut-sahur-app:
        build:
            context: .
            dockerfile: docker/DockerFile
        image: kejut-sahur-app:latest
        container_name: "kejut-sahur-app"
        platform: linux/amd64
        networks:
            - app-network
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - 5174:5174
        volumes:
            - ".:/var/www/html"
            - "./docker/php.ini:/usr/local/etc/php/conf.d/php.ini"
    nginx:
        image: nginx:alpine
        container_name: kejut-sahur-nginx
        platform: linux/amd64
        restart: unless-stopped
        ports:
            - 8032:80
        working_dir: "/var/www/html"
        volumes:
            - ".:/var/www/html"
            - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
        networks:
            - app-network
        depends_on:
            - kejut-sahur-app
    mariadb:
        image: mariadb:11.8.2
        container_name: kejut-sahur-mariadb
        platform: linux/amd64
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
            MARIADB_DATABASE: "${DB_DATABASE}"
            MARIADB_USER: "${DB_USERNAME}"
            MARIADB_PASSWORD: "${DB_PASSWORD}"
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
        ports:
            - 3331:3306
        volumes:
            - "vol-kejut-sahur-mariadb:/var/lib/mysql"
        networks:
            - app-network
    redis:
        image: redis:8.0-alpine
        container_name: kejut-sahur-redis
        platform: linux/amd64
        restart: unless-stopped
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "6392:6379"
        networks:
            - app-network
    mailpit:
        image: axllent/mailpit:latest
        container_name: kejut-sahur-mailpit
        platform: linux/amd64
        ports:
            - 1051:1025
            - 8051:8025
        networks:
            - app-network
    
networks:
    app-network:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.131.0/24
volumes:
    vol-kejut-sahur-mariadb:
        driver: local